apt-get install cmake 
apt-get install make 
apt-get install g++ 
apt-get install libx11-dev 
apt-get install libxi-dev 
apt-get install libgl1-mesa-dev 
apt-get install libglu1-mesa-dev 
apt-get install libxrandr-dev 
apt-get install libxext-dev